finished coding upto batching/running training. getting the below erorr in batching. need to ask fan or becky. although i notice that when i was printing the batches it was showing a list of labels alone as a batch..weird, i thought it was like datapoint,labels that we needed to pass
TypeError: an integer is required (got type str)